### ISSUE TITLE
Waybar config

### ISSUE THREAD

**Issue by edpyt** [rishav12s/Eternal-Arctic#1]
Hello, thanks for this theme, it's really great!  
Can you please share your waybar config and how to setup it for hyprdots?

**Comment by sitolam** [comment]
+1
Waybar config in the screenshots is not applied

**Comment by rishav12s** [comment]
Its the default HyDE waybar with some of my personal customizations and some from a old pr done in the hyprdots repo

you cant change waybar style like that from a theme its hardcoded stuff in hyprdots/hyde basically

Here you go : https://github.com/rishav12s/HyDE-dots/tree/main/waybar

dont forget to star the theme repos takes time to make themes lol 😉😁

@sitolam @edpyt

**Comment by sitolam** [comment]
> Its the default HyDE waybar with some of my personal customizations and some from a old pr done in the hyprdots repo
> 
> you cant change waybar style like that from a theme its hardcoded stuff in hyprdots/hyde basically
> 
> Here you go : https://github.com/rishav12s/HyDE-dots/tree/main/waybar
> 
> dont forget to star the theme repos takes time to make themes lol 😉😁
> 
> @sitolam @edpyt 

Thx, it's sad that the waybar style can't be shared. ⭐

**Comment by rishav12s** [comment]
> Thx, it's sad that the waybar style can't be shared. ⭐


yea waybar needs an overhaul the  hyde repo will be shifted to new a fork (as the owner is afk) where all these needed stuff will be implemented 

will take time tho

**Comment by edpyt** [comment]
@rishav12s thx!

gave stars to your repositories!
